<?php

use Drupal\Core\Database\Database;

/**
 * Implements hook_cron().
 */
function site_subscription_cron() {
    $connection = \Drupal::database();
    $config = \Drupal::config('site_subscription.settings');
    $number = $config->get('number');
    
    // Считывает значение из системной конфигурации.
    $site_subscription_count = \Drupal::state()->get('site_subscription_count');
    if (!$site_subscription_count) {
        $site_subscription_count = 0;
    }

    // Перечень подписок для обработки.
    $query = $connection->select('site_subscription', 'n');
    $query->fields('n');
    $query->range($site_subscription_count, $number);
    $result = $query->execute();

    foreach ($result as $row) {       
        $mail = $row->mail;
        \Drupal::logger('site_subscription')->notice($mail);
    }

    // Сохраняет значение в системную конфигурацию.
    $site_subscription_count = $site_subscription_count + $number;
    \Drupal::state()->set('site_subscription_count', $site_subscription_count);       
}


/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 *
 * Adds the book form element to the node form.
 *
 * @see book_pick_book_nojs_submit()
 */
function subscription_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  $account = \Drupal::currentUser();
  $access = $account->hasPermission('administer book outlines');
  if (!$access) {
    if ($account->hasPermission('add content to books') && ((!empty($node->book['bid']) && !$node->isNew()) || book_type_is_allowed($node->getType()))) {
      // Already in the book hierarchy, or this node type is allowed.
      $access = TRUE;
    }
  }

  if ($access) {
    $collapsed = !($node->isNew() && !empty($node->book['pid']));
    $form = \Drupal::service('book.manager')->addFormElements($form, $form_state, $node, $account, $collapsed);
    // The "js-hide" class hides submit button when Javascript is enabled.
    $form['book']['pick-book'] = array(
      '#type' => 'submit',
      '#value' => t('Change book (update list of parents)'),
      '#submit' => array('book_pick_book_nojs_submit'),
      '#weight' => 20,
      '#attributes' => array(
        'class' => array(
          'js-hide',
        ),
      ),
    );
    $form['#entity_builders'][] = 'book_node_builder';
  }
}